### ISSUE TITLE
Problem Regelung Geschwindigkeit

### ISSUE THREAD

**Issue by BennyBread** [timo1235/cnc-werkstatt#4]
Hallo. Ich weiß nicht ob das ein Problem des CNC Shields V2 ist, oder Estlcam. Ich versuche mal aber mein Problem zu erklären:
Wir sind gerade dabei eine unserer beiden (Freund und ich bauen die gleiche CNC) Einzurichten und irgendwie stimmt die Drehzahleinstellung nicht.

Wir haben eine Vevor 2.2kW Spindel mit  mit passendem Vevor FU. Die Spindel kann 24000 upm.
Der FU hat 400Hz PWM Frequenz. In Estlcam kann man aber nur Feste Werte Einstellen!? (oder ich mach was falsch)
Ein Wert von Estlcam ist 250Hz. Das habe ich am FU auch in dne Settings versucht Einzustellen.. (Allerdings ist es mit 400Hz genauso falsch.)

Zunächst ist es so, der FU hat zwei Eingänge einmal 0-10v und einmal 0-5V.

Also VCC Ausgang auf den 0-5V Eingang vom FU und den JP3 hab ich auch 5V bzw. 10V eingestellt. (je nachdem an welchem Eingang ich es angeklemmt hab.)

Die 100% stimmen, aber wenn ich z.B. 50 % einstelle zeigt der FU nicht 12000 (Respektive 125Hz) an sondern einen zu geringen Wert. (ca. die Hälfte davon)

Im Anhang ein paar Bilder vom 0-5V versuch. (Die FU Anzeige kann man auf RPM oder Hz einstellen was ich gemacht habe.
Die Spannung hab ich mit einem Multimeter zusätzlich gemessen. Ein Oszi ist leider nicht vorhanden.

```
Estlcam       FU Hz IST     FU Hz Soll       erwartete Spannung       IST-Spannung           
 ( 24000
  250Hz)

100%           250            250                 5V                      4.97V
50%           66.3            125                 2.5V                   1,19V
10%           0.00            25                  0.5V                     0V

```
Wir haben verschiedene Einstellungen ausprobiert, es allerdings nicht hinbekommen. Vielleicht hast Du eine Idee??

Auf jeden Fall ist die Spannung bei den eingestellten Prozentwerten zu gering. Frage ist nur Board, oder Estlcam?

<a href="https://postimg.cc/ppLJvRFd" target="_blank"><img src="https://i.postimg.cc/ppLJvRFd/10-Prozent-am-FU.jpg" alt="10-Prozent-am-FU"/></a>
<a href="https://postimg.cc/2bxnpKjv" target="_blank"><img src="https://i.postimg.cc/2bxnpKjv/Estlcam-10-Prozent.jpg" alt="Estlcam-10-Prozent"/></a><br/><br/>

<a href="https://postimg.cc/rDv154Yd" target="_blank"><img src="https://i.postimg.cc/rDv154Yd/50-Prozent-am-FU.jpg" alt="50-Prozent-am-FU"/></a>
<a href="https://postimg.cc/1nSDjQSs" target="_blank"><img src="https://i.postimg.cc/1nSDjQSs/Estlcam-50-Prozent.jpg" alt="Estlcam-50-Prozent"/></a>

<a href="https://postimg.cc/zHXKqF3Q" target="_blank"><img src="https://i.postimg.cc/zHXKqF3Q/100-Prozent-am-FU.jpg" alt="100-Prozent-am-FU"/></a>
<a href="https://postimg.cc/f3mxCb68" target="_blank"><img src="https://i.postimg.cc/f3mxCb68/Estlcam-100-Prozent.jpg" alt="Estlcam-100-Prozent"/></a><br/><br/>

**Comment by timo1235** [comment]
Hi, 
auf den Bildern ist am VCC Ausgang vom OCS2 für den FU nichts angeschlossen, wenn ich das richtig sehe.
Die Kabel gehen in den PWM Ausgang. Der FU braucht aber ein analoges Signal, das ist an VCC.

In Estlcam die default Einstellungen lassen: 8000Hz... Beachte auch das "Unteres Drehzahllimit", wenn du darüber hoverst ist da noch eine Erklärung.

**Comment by BennyBread** [comment]
Du hast Recht, auf dem Bild ist es tatsächlich noch falsch angeschlossen. Wir haben es später dann auf VCC angeklemmt. Hat aber nichts gebracht. Das mit den 8000 werden wir mal probieren.
